-- -- Enable UUID generation (Standard for Postgres)
-- CREATE
-- EXTENSION IF NOT EXISTS "uuid-ossp";
--
--
-- -- 1. AVATARS (Static Assets)
-- CREATE TABLE avatars
-- (
--     id   SERIAL PRIMARY KEY,
--     path VARCHAR(255) NOT NULL,
--     name VARCHAR(50)
-- );
--
-- -- 2. USERS
-- CREATE TABLE users
-- (
--     id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
--     email            VARCHAR(255) NOT NULL UNIQUE,
--     username         VARCHAR(50)  NOT NULL UNIQUE,
--     password_hash    VARCHAR(255) NOT NULL,
--     first_name       VARCHAR(100),
--     last_name        VARCHAR(100),
--     chosen_avatar_id INT REFERENCES avatars (id)
--
--         -- Auditing
--         version          INT                   DEFAULT 0, -- For Optimistic Locking
--     created_at       TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
--     updated_at       TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
--     deleted_at       TIMESTAMP                            -- Soft Delete
-- );
--
-- -- 3. COURSES
-- CREATE TABLE courses
-- (
--     id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
--     author_id     UUID         NOT NULL REFERENCES users (id),
--     title         VARCHAR(150) NOT NULL,
--     description   TEXT,
--     thumbnail_url VARCHAR(255),
--     is_published  BOOLEAN          DEFAULT FALSE,
--     status        VARCHAR(20)  NOT NULL,
--
--     created_at    TIMESTAMP        DEFAULT CURRENT_TIMESTAMP,
--     updated_at    TIMESTAMP        DEFAULT CURRENT_TIMESTAMP
-- );
--
-- -- 4. LESSONS (Grouping Unit 1 - e.g., "Modules" or "Chapters")
-- CREATE TABLE lessons
-- (
--     id        UUID PRIMARY KEY      DEFAULT uuid_generate_v4(),
--     course_id UUID         NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
--     title     VARCHAR(150) NOT NULL,
--     position  INT          NOT NULL DEFAULT 0 -- CRITICAL: Defines order of chapters
-- );
--
-- -- 5. SECTIONS (Grouping Unit 2 - e.g., "The actual Page")
-- CREATE TABLE sections
-- (
--     id        UUID PRIMARY KEY      DEFAULT uuid_generate_v4(),
--     lesson_id UUID         NOT NULL REFERENCES lessons (id) ON DELETE CASCADE,
--     title     VARCHAR(150) NOT NULL,
--     position  INT          NOT NULL DEFAULT 0 -- CRITICAL: Defines order of pages inside a chapter
-- );
--
-- -- 6. COMPONENTS (The Atoms - This is where JSONB lives)
-- CREATE TABLE components
-- (
--     id         UUID PRIMARY KEY     DEFAULT uuid_generate_v4(),
--     section_id UUID        NOT NULL REFERENCES sections (id) ON DELETE CASCADE,
--
--     -- Discriminator: 'TEXT', 'VIDEO', 'CODE_TASK', 'QUIZ'
--     type       VARCHAR(50) NOT NULL,
--
--     -- The Dynamic Payload
--     content    JSONB       NOT NULL,
--
--     position   INT         NOT NULL DEFAULT 0 -- CRITICAL: Order of blocks on the page
-- );
--
-- -- 7. ENROLLMENTS
-- CREATE TABLE enrollments
-- (
--     user_id       UUID NOT NULL REFERENCES users (id),
--     course_id     UUID NOT NULL REFERENCES courses (id),
--
--     progress      FLOAT     DEFAULT 0.0, -- 0 to 100%
--     last_accessed TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--
--     PRIMARY KEY (user_id, course_id)
-- );
--
-- -- Indexes for JSONB performance
-- CREATE INDEX idx_components_content ON components USING GIN (content);